version: '2'
services:
  postgres:
    container_name: itmo-quest-service
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=itmo-quest-service
    ports:
      - "7560:5432"
    restart: unless-stopped
    volumes:
      - ./log-directory:/var/lib/postgresql/data